apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-canary-service
spec:
  selector:
    app: {{ .Release.Name }}-canary-app
  ports:
    - protocol: TCP
      port: {{ .Values.canary.srcPort }}
      targetPort: {{ .Values.canary.targetPort}}
  type: NodePort

